steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: TestAndBuild
    args:
      - 'build'
      - '-t'
      - 'asia.gcr.io/$PROJECT_ID/tech-test2:$SHORT_SHA'
      - '--build-arg'
      - 'ci_sha=$COMMIT_SHA'
      - '--build-arg'
      - 'ci_description=pre-interview technical test, CloudBuild does not have commit message?'
      - '--build-arg'
      - 'ci_version=1.0.0'
      - '.'
